name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy-messages:
    runs-on: ubuntu-latest
    name: apps/messages/
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./apps/messages/

  deploy-svelte-lucia:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: apps/svelte-lucia/
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
        working-directory: ./apps/svelte-lucia/
      - uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: svelte-lucia
          directory: ./apps/svelte-lucia/.svelte-kit/cloudflare/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
